version: "3"

services:
  sqs:
    image: softwaremill/elasticmq-native:latest
    ports:
      - "9324:9324"
    volumes:
      - ./containers/elasticmq/app.conf:/opt/elasticmq.conf
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
