[main]
stat_server_port = {{or .stat_server_port 5956}}
log_level        = "{{or .log_level "INFO"}}"

[worker]
url               = "{{.worker_url}}"
max_process_count = {{or .max_process_count 1}}

{{if .healthcheck_url -}}
[worker.healthcheck]
url             = "{{.healthcheck_url}}"
max_elapsed_sec = {{or .healthcheck_max_elapsed_sec 10}}
max_request_ms  = {{or .healthcheck_max_request_ms 1000}}
{{- end}}

[sqs]
account_id    = "{{.aws_account_id}}"
region        = "{{.aws_region}}"
queue_name    = "{{.queue_name}}"
concurrency   = {{or .concurrency 1}}
wait_time_sec = {{or .wait_time_sec 20}}
