[worker]
interval_seconds={{or .interval_seconds 20}}
max_process_count={{or .max_process_count 5}}
worker_url="{{.worker_url}}"

[stat]
server_port={{.stat_server_port}}

[sqs]
account_id="{{.aws_account_id}}"
region="{{.aws_region}}"
queue_name="{{.sqs_queue_name}}"
