[worker]
interval_seconds={{or .interval_seconds 1}}
max_process_count={{or .max_process_count 5}}
job_url="{{.job_url}}"

[stat]
server_port={{.stat_server_port}}

[sqs]
queue_url="{{.sqs_queue_url}}"
region={{.sqs_region}}
